version: '3.0'
services:
  client:
    image: delivery-client
    restart: always
    ports:
      - 8080:8080
  server:
    image: delivery-server
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: 'db'
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config: